routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('Home','HomeController');

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Models/news.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class news extends Model
{
     protected $table =  'new';
   protected $fillable = ['name','information_article','fk_type_id'];
   protected  $guarded = ['id'];
}

app/Models/perfil.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class perfil extends Model
{
     protected $table =  'perfil';
   protected $fillable = ['general_information','portfolio_information','images','fk_page_id'];
   protected  $guarded = ['id'];
}

app/Models/portfolio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class portfolio extends Model
{
	 protected $table =  'portfolio';
   protected $fillable = ['portfolio_name','description','images_portfolio'];
   protected  $guarded = ['id'];
    }

app/Models/type.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class type extends Model
{
     protected $table =  'type';
   protected $fillable = ['name'];
   protected  $guarded = ['id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','last_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\news;
use App\Models\perfil;
use App\Models\portfolio;
use App\Models\type;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(){
        
    }


    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $noticia = news::all();
        $perfil = perfil::all();
        $portafolio = portfolio::all();
        $type = type::all();
        
        return view('home')
        ->with('noticia',$noticia)
        ->with('perfil', $perfil)
        ->with('portafolio',$portafolio)
        ->with('type',$type);


    }
    public function show($id)
    {
        $perfil = perfil::find($id);

        return view('perfiledit')
        ->with('perfil', $perfil);
    }
}

resources/views/articles.blade.php
@extends('layouts.app')

@section('header')

@endsection

@section('content')
@if (Auth::guest())
    @else
        <div class="pull-right">
             <a data-toggle="modal" data-target="#New" data-placement="bottom" title="Nuevo"><i class="btn fa fa-plus fa-4x" aria-hidden="true"></i></a>
        </div>
@endif
    <section class="main-section" id="service">
        <center>
            <h1>Articulos</h1>
        </center>
        <div class="container">
            <div class="row">
                @include('flash::message')
                @foreach ($article as $article)
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            {{$article->name}}
                            <div class="pull-right"> Tags:
                                @foreach ($article->tags as $tags)
                                    {{$tags->name}}.
                                @endforeach
                            </div>
                        </div>
                            <div class="panel-body">
                                <h3>{{$article->description}}</h3>
                            </div>
                            <div class="panel-footer">
                                @if (Auth::guest())
                                <p>Categoria:  {{$article->category->name}}</p>
                                @else
                                <p>Categoria:  {{$article->category->name}}</p>
                                    <center>

                                        <a href="{{route('Article.edit', $article->id)}}" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="btn fa fa-pencil fa-2x" aria-hidden="true"></i></a>
                                        <a href="{{route('Article.destroy', $article->id)}}" data-toggle="tooltip" data-placement="bottom" title="Eliminar"><i class="btn fa fa-trash fa-2x" aria-hidden="true"></i></a>
                                    </center>
                                @endif
                            </div>
                        </div>

                @endforeach
            </div>
        </div>
    </section>

<!--
    Mis Modelas
-->
<!-- Agregar al portafolio -->
  <div class="modal fade" id="New" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Nuevo articulo</h4>
        </div>
        <div class="modal-body">
            {!! Form::open(['route' => 'Article.store', 'method' => 'POST', 'files' => true]) !!}
                

                <div class="form-group">
                    {!! Form::label('name_project', 'Nombre') !!}
                    {!! Form::text('name', null, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre del articulo']) !!}
                </div>
                                        
                <div class="form-group">
                    {!! Form::label('description_project', 'Descripcion') !!}
                    {!! Form::textarea('description', null, ['class' =>'form-control textarea-academic', 'requerid', 'placeholder' => 'Descripcion del articulo']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('category_id', 'Prioridad',[ 'class' => 'col-md-4 control-label']) !!}
                    {!! Form::select('category_id', $category, null, ['class' => 'form-control category-select ','placeholder' => 'Seleccione una categoria', 'required']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('fk_priority_id', 'Requisitos de la historia',[ 'class' => ' control-label']) !!}
                    {!! Form::select('tag[]', $tag, null, ['class' => 'form-control tag-select ','placeholder' => 'Seleccione algunos tags', 'required','multiple']) !!}
                </div>
                <div class="form-group">
                    {!! Form::hidden('blog_id', 1) !!}
                </div>
        </div>
        <div class="modal-footer">
            <center>
                {!! Form::submit('Guardar', ['class' =>'btn btn-success']) !!}
            </center>
          {!! Form::close() !!}
        </div>
      </div>
      
    </div>
  </div>

@endsection

@section('js')
<script>
    $('#New').on('shown.bs.modal', function () {
        $('.tag-select', this).chosen({
        });

        $('.category-select', this).chosen({
        }); 
    });

    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });

    $('.textarea-academic').trumbowyg();
</script>
@endsection

resources/views/categories.blade.php
@extends('layouts.app')

@section('header')

@endsection

@section('content')
@if (Auth::guest())
    @else
        <div class="pull-right">
             <a data-toggle="modal" data-target="#New" data-placement="bottom" title="Nuevo"><i class="btn fa fa-plus fa-4x" aria-hidden="true"></i></a>
        </div>
@endif
    <section class="main-section" id="service">
        <center>
            <h1>Mis categorias</h1>
        </center>
        <div class="container">
            <div class="row">
                @include('flash::message')
                @foreach ($catefory as $catefory)
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <center>
                                    <h3><a href="#">{{$catefory->name}}</a></h3>
                                </center>
                            </div>
                            
                                <div class="panel-footer"> 
                                    <center>
                                        @if (Auth::guest())
                                            @else
                                                <a href="{{route('Category.edit', $catefory->id)}}" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="btn fa fa-pencil fa-2x" aria-hidden="true"></i></a>
                                                <a href="{{route('Category.destroy', $catefory->id)}}" data-toggle="tooltip" data-placement="bottom" title="Eliminar"><i class="btn fa fa-trash fa-2x" aria-hidden="true"></i></a> 
                                            @endif
                                            
                                            
                                    </center>
                                    </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>

<!--
    Mis Modelas
-->
<!-- Agregar al portafolio -->
  <div class="modal fade" id="New" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Nueva categoria</h4>
        </div>
        <div class="modal-body">
            {!! Form::open(['route' => 'Category.store', 'method' => 'POST', 'files' => true]) !!}
                

                <div class="form-group">
                    {!! Form::label('name_project', 'Nombre') !!}
                    {!! Form::text('name', null, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre de la categoria']) !!}
                </div>
        </div>
        <div class="modal-footer">
            <center>
                {!! Form::submit('Guardar', ['class' =>'btn btn-success']) !!}
            </center>
          {!! Form::close() !!}
        </div>
      </div>
      
    </div>
  </div>

@endsection

@section('js')
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });

    $('.textarea-academic').trumbowyg();
</script>
@endsection

resources/views/edit/article.blade.php
@extends('layouts.app')

@section('header')

@endsection

@section('content')
<section class="main-section" id="service">

                    <div class="container">
                        
                            {!! Form::open(['route' => ['Article.update', $article->id], 'method' => 'PUT', 'files' => true]) !!}

                                <div class="form-group">
                                    {!! Form::label('name_project', 'Nombre') !!}
                                    {!! Form::text('name', $article->name, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre del articulo']) !!}
                                </div>
                                                        
                                <div class="form-group">
                                    {!! Form::label('description_project', 'Descripcion') !!}
                                    {!! Form::textarea('description', $article->description, ['class' =>'form-control textarea-academic', 'requerid', 'placeholder' => 'Descripcion del articulo']) !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::label('category_id', 'Prioridad',[ 'class' => 'col-md-4 control-label']) !!}
                                    {!! Form::select('category_id', $category, $article->category_id, ['class' => 'form-control category-select ','placeholder' => 'Seleccione una categoria', 'required']) !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::label('fk_priority_id', 'Requisitos de la historia',[ 'class' => ' control-label']) !!}
                                    {!! Form::select('tag[]', $tag, $article->tags, ['class' => 'form-control tag-select ','placeholder' => 'Seleccione algunos tags', 'required','multiple']) !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::hidden('blog_id', 1) !!}
                                </div>

                                <center>
                                    {!! Form::submit('Guardar', ['class' =>'btn btn-success']) !!}
                                </center>      
                            {!! Form::close() !!}
                    </div>   
    </section>
@endsection

@section('js')
<script>
        $('.tag-select', this).chosen({
        });

        $('.category-select', this).chosen({
        }); 
        
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });

    $('.textarea-academic').trumbowyg();
</script>
@endsection

resources/views/edit/category.blade.php
@extends('layouts.app')

@section('header')

@endsection

@section('content')
<section class="main-section" id="service">

                    <div class="container">
                        @include('flash::message')
                            {!! Form::open(['route' => ['Category.update', $category->id], 'method' => 'PUT', 'files' => true]) !!}
                               
                               <div class="form-group">
                                    {!! Form::label('name_project', 'Nombre') !!}
                                    {!! Form::text('name', $category->name, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre de la categoria']) !!}
                                </div>
                                <center>
                                    {!! Form::submit('Guardar', ['class' =>'btn btn-success']) !!}
                                </center>
                                    
                                
                            {!! Form::close() !!}
                    </div>                
    </section>
@endsection

@section('js')
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });

    $('.textarea-academic').trumbowyg();
</script>
@endsection

resources/views/edit/portafolio.blade.php
@extends('layouts.app')

@section('header')

@endsection

@section('content')
<section class="main-section" id="service">
         @if (Auth::guest())
                    <div class="container">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3><a href="#">{{$image->portafolio->name_project}}</a></h3>
                            </div>
                            <div class="panel-body">
                                <center><img src="/images/portafolio/{{$image->name}}" ></center>
                                <div>
                                    <h4>{{$image->portafolio->description_project}}</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    @else
                    <div class="container">
                        @include('flash::message')
                            {!! Form::open(['route' => ['Portafolio.update', $image->id], 'method' => 'PUT', 'files' => true]) !!}
                                <div class="form-group">
                                    {!! Form::label('name_project', 'Nombre') !!}
                                    {!! Form::text('name_project', $image->portafolio->name_project, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre del portafolio']) !!}
                                </div>                  
                                <div class="form-group">
                                    {!! Form::label('description_project', 'Descripcion del portafolio') !!}
                                    {!! Form::textarea('description_project', $image->portafolio->description_project, ['class' =>'form-control textarea-academic', 'requerid', 'placeholder' => 'Descripcion del portafolio']) !!}
                                </div>
                                <div>
                                    <center><img src="/images/portafolio/{{$image->name}}" width="1000" ></center>
                                </div>
                                <div class="form-group">
                                    {!! Form::hidden('blog_id', 1) !!}
                                </div>

                                <center>
                                    {!! Form::submit('Guardar', ['class' =>'btn btn-success']) !!}
                                </center>
                                    
                                
                            {!! Form::close() !!}
                    </div>
                        
                @endif

                
    </section>
@endsection

@section('js')
<script>
    
</script>
@endsection

resources/views/edit/tag.blade.php
@extends('layouts.app')

@section('header')

@endsection

@section('content')
<section class="main-section" id="service">

                    <div class="container">
                        @include('flash::message')
                            {!! Form::open(['route' => ['Tag.update', $tag->id], 'method' => 'PUT', 'files' => true]) !!}
                               
                               <div class="form-group">
                                    {!! Form::label('name_project', 'Nombre') !!}
                                    {!! Form::text('name', $tag->name, ['class' =>'form-control textarea-personal', 'requerid', 'placeholder' => 'Nombre del tag']) !!}
                                </div>
                                <center>
                                    {!! Form::submit('Guardar', ['class' =>'btn btn-success']) !!}
                                </center>
                                    
                                
                            {!! Form::close() !!}
                    </div>                
    </section>
@endsection

@section('js')
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });

    $('.textarea-academic').trumbowyg();
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app2')

<body>

        <!-- Header -->
            <div id="header">

                <div class="top">

                    <!-- Logo -->
                        <div id="logo">
                            <span class="image avatar48"><img src="{{asset('tema1/images/avatar.jpg')}}" alt="" /></span>
                            <h1 id="title">Juan Nicolas Buitrago Ruiz</h1>
                            <p>jnbuitrago6@misena.edu.co</p>
                        </div>

                    <!-- Nav -->
                        <nav id="nav">
                            <!--

                                Prologue's nav expects links in one of two formats:

                                1. Hash link (scrolls to a different section within the page)

                                   <li><a href="#foobar" id="foobar-link" class="icon fa-whatever-icon-you-want skel-layers-ignoreHref"><span class="label">Foobar</span></a></li>

                                2. Standard link (sends the user to another page/site)

                                   <li><a href="http://foobar.tld" id="foobar-link" class="icon fa-whatever-icon-you-want"><span class="label">Foobar</span></a></li>

                            -->
                            <ul>
                                <li><a href="#top" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-home">Introduccion</span></a></li>
                                <li><a href="#portfolio" id="portfolio-link" class="skel-layers-ignoreHref"><span class="icon fa-th">Portafolio</span></a></li>
                                <li><a href="#about" id="about-link" class="skel-layers-ignoreHref"><span class="icon fa-user">Acerca de mi </span></a></li>
                                <li><a href="#contact" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope">Contacto</span></a></li>
                                <li>@if (Auth::guest())
                                    @else
                            <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                        @endif</li>
                            </ul>
                        </nav>

                </div>

                <div class="bottom">

                    <!-- Social Icons -->
                        <ul class="icons">
                            <li><a href="https://twitter.com/NikolasIzR" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                            <li><a href="https://www.facebook.com/juannikolas.buitragoruiz" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                            <li><a href="https://gitlab.com/JuanRuiz10" class="fa fa-gitlab"><span class="label"></span></a></li>
                           
                        </ul>

                </div>

            </div>

        <!-- Main -->
            <div id="main">

                <!-- Intro -->
                    <section id="top" class="one dark cover">
                        <div class="container">

                            <header>
                                <h2 class="alt">Hola Amigos¡ <strong>Bienvenidos</strong>, a mi Blog WEB
                                un sitio diseñado para interactuar mas con ustedes y mostrarles un poco de mi trabajo</a>.</h2>
                                <p><br />
                                
                            </header>

                            <footer>
                                <a href="#portfolio" class="button scrolly">Empecemos</a>
                            </footer>

                        </div>
                    </section>

                <!-- Portfolio -->
                    <section id="portfolio" class="two">
                        <div class="container">
                                
                            <header>
                                <h2>Portafolio</h2>
                            </header>

                            <p>Estos son algunos de mis proyectos relizados.</p>

                            <div class="row">
                                 @if(Auth::guest())
                                 
                                 @else
                                    <div class="pull-right">
                                        <a data-toggle="modal" data-target="#New" data-placement="bottom" title="Nuevo"><i class="btn fa fa-plus fa-4x" aria-hidden="true"></i></a>
                                    </div>

                                    <!-- Agregar al portafolio -->
                         <div class="modal fade" id="New" role="dialog">
                            <div class="modal-dialog">
    
                     <!-- Modal content-->
                             <div class="modal-content">
                                <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Nueva imagen</h4>
                        </div>
                            <div class="modal-body">
                    <p>HOLA COMO ESTAS BEBE</p>
                                </div>
                    </div>
                        </div>
                            </div>


                                <div class="4u 12u$(mobile)">
                                    <article class="item">
                                        <a href="#" class="image fit"><img src="{{asset('tema1/images/pic02.jpg')}}" alt="" /></a>
                                        <header>
                                            <h3>Ipsum Feugiat</h3>
                                        </header>
                                    </article>
                                    <article class="item">
                                        <a href="#" class="image fit"><img src="{{asset('tema1/images/pic03.jpg')}}" alt="" /></a>
                                        <header>
                                            <h3>Rhoncus Semper</h3>
                                        </header>
                                    </article>
                                </div>
                                <div class="4u 12u$(mobile)">
                                    <article class="item">
                                        <a href="#" class="image fit"><img src="{{asset('tema1/images/pic04.jpg')}}" alt="" /></a>
                                        <header>
                                            <h3>Magna Nullam</h3>
                                        </header>
                                    </article>
                                    <article class="item">
                                        <a href="#" class="image fit"><img src="{{asset('tema1/images/pic05.jpg')}}" alt="" /></a>
                                        <header>
                                            <h3>Natoque Vitae</h3>
                                        </header>
                                    </article>
                                </div>
                                <div class="4u$ 12u$(mobile)">
                                    <article class="item">
                                        <a href="#" class="image fit"><img src="{{asset('tema1/images/pic06.jpg')}}" alt="" /></a>
                                        <header>
                                            <h3>Dolor Penatibus</h3>
                                        </header>
                                    </article>
                                    <article class="item">
                                        <a href="#" class="image fit"><img src="{{asset('tema1/images/pic07.jpg')}}" alt="" /></a>
                                        <header>
                                            <h3>Orci Convallis</h3>
                                        </header>
                                    </article>
                                </div>
                            </div>

                        </div>
                    </section>

                <!-- About Me -->
                    <section id="about" class="three">
                        <div class="container">

                            @foreach ($perfil as $perfil)
                            <div>
                                 @if(Auth::guest())

                                 @else
                                 <a href="{{route('Home.show',$perfil->id)}}">EDITAR</a>
                                 <a href="{{route('Home.destroy',$perfil->id)}}">ELIMINAR</a>

                                @endif
                                <p>Información General</p>
                                <p>{!! $perfil->general_information !!}</p>
                                <p>Información del Portafolio</p>
                                <p>{!! $perfil->portfolio_information !!}</p>
                            </div>
                                
                            
                            @endforeach

                        </div>
                    </section>

                <!-- Contact -->
                    <section id="contact" class="four">
                        <div class="container">

                            <header>
                                <h2>Contact</h2>
                            </header>

                            <p>Enviame tus preguntas ,sugerencias o criticas </p>

                            <form method="post" action="#">
                                <div class="row">
                                    <div class="6u 12u$(mobile)"><input type="text" name="name" placeholder="Name" /></div>
                                    <div class="6u$ 12u$(mobile)"><input type="text" name="email" placeholder="Email" /></div>
                                    <div class="12u$">
                                        <textarea name="message" placeholder="Message"></textarea>
                                    </div>
                                    <div class="12u$">
                                        <input type="submit" value="Send Message" />
                                    </div>
                                </div>
                            </form>

                        </div>
                    </section>

            </div>

        <!-- Footer -->
            <div id="footer">

                <!-- Copyright -->
                    <ul class="copyright">
                        <li>&copy; Untitled. All rights reserved.</li><li>Design: Juan Ruiz</a></li>
                    </ul>

            </div>

        <!-- Scripts -->
            <script src="{{asset('tema1/assets/js/jquery.min.js')}}"></script>
            <script src="{{asset('tema1/assets/js/jquery.scrolly.min.js')}}"></script>
            <script src="{{asset('tema1/assets/js/jquery.scrollzer.min.js')}}"></script>
            <script src="{{asset('tema1/assets/js/skel.min.js')}}"></script>
            <script src="{{asset('tema1/assets/js/util.js')}}"></script>
            <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
            <script src="{{asset('tema1/assets/js/main.js')}}"></script>

    </body>